
CREATE SCHEMA IF NOT EXISTS `atelie` DEFAULT CHARACTER SET utf8 ;
USE `atelie` ;

CREATE TABLE IF NOT EXISTS `atelie`.`PRODUTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COD` VARCHAR(13) NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `PRECO` DECIMAL(2) NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `atelie`.`VENDA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATAHORA` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `atelie`.`PRODUTO_VENDIDO` (
  `PRODUTO_ID` INT NOT NULL,
  `VENDA_ID` INT NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `PRECO` DECIMAL(2) NOT NULL,
  `DESCONTO` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`PRODUTO_ID`, `VENDA_ID`),
  CONSTRAINT `fk_PRODUTO_has_VENDA_PRODUTO`
    FOREIGN KEY (`PRODUTO_ID`)
    REFERENCES `atelie`.`PRODUTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_has_VENDA_VENDA1`
    FOREIGN KEY (`VENDA_ID`)
    REFERENCES `atelie`.`VENDA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;